[package]
name = "wayland-cursor"
version = "0.26.1"
documentation = "https://smithay.github.io/wayland-rs/wayland_client/"
repository = "https://github.com/smithay/wayland-rs"
authors = ["Victor Berger <victor.berger@m4x.org>"]
license = "MIT"
edition = "2018"
categories = ["gui", "api-bindings"]
keywords = ["wayland", "client"]
description = "Bindings to libwayland-cursor."

[badges]
travis-ci = { repository = "Smithay/wayland-rs" }

[dependencies]
wayland-client = { version = "0.26.1", path = "../wayland-client" }
xcursor = "0.1"
xcur = "0.1"
nix = "0.17.0"
