[package]
name = "wayland-cursor"
version = "0.28.3"
documentation = "https://smithay.github.io/wayland-rs/wayland_client/"
repository = "https://github.com/smithay/wayland-rs"
authors = ["Victor Berger <victor.berger@m4x.org>"]
license = "MIT"
edition = "2018"
categories = ["gui", "api-bindings"]
keywords = ["wayland", "client"]
description = "Bindings to libwayland-cursor."
readme = "README.md"

[dependencies]
wayland-client = { version = "0.28.3", path = "../wayland-client" }
xcursor = "0.3.1"
nix = "0.18.0"
