[package]
name = "wayland-cursor"
version = "0.30.0-beta.10"
documentation = "https://docs.rs/wayland-cursor/"
repository = "https://github.com/smithay/wayland-rs"
authors = ["Victor Berger <victor.berger@m4x.org>"]
license = "MIT"
edition = "2018"
categories = ["gui", "api-bindings"]
keywords = ["wayland", "client"]
description = "Bindings to libwayland-cursor."
readme = "README.md"

[dependencies]
wayland-client = { version = "=0.30.0-beta.10", path = "../wayland-client" }
xcursor = "0.3.1"
nix = { version = "0.24.1", default-features = false, features = ["mman"] }
