[package]
name = "wayland-egl"
version = "0.30.0-beta.12"
documentation = "https://docs.rs/wayland-egl/"
repository = "https://github.com/smithay/wayland-rs"
authors = ["Victor Berger <victor.berger@m4x.org>"]
license = "MIT"
edition = "2018"
categories = ["gui", "api-bindings"]
keywords = ["wayland", "client"]
description = "Bindings to libwayland-egl."
readme = "README.md"

[dependencies]
wayland-backend = { version = "=0.1.0-beta.12", path = "../wayland-backend", features = ["client_system"] }
wayland-sys = { version = "=0.30.0-beta.12", path="../wayland-sys", features = ["egl"] }
thiserror = "1.0.30"