[package]
name = "wayland-commons"
version = "0.21.4"
authors = ["Victor Berger <victor.berger@m4x.org>"]
repository = "https://github.com/smithay/wayland-rs"
documentation = "https://smithay.github.io/wayland-rs/wayland_commons/"
description = "Common types and structures used by wayland-client and wayland-server."
license = "MIT"
categories = ["gui", "api-bindings"]
keywords = ["wayland"]

[badges]
travis-ci = { repository = "Smithay/wayland-rs" }

[dependencies]
wayland-sys = { version = "0.21.4", path = "../wayland-sys", optional = true }
nix = "0.11"

[features]
native_lib = [ "wayland-sys" ]
