[package]
name = "wayland-commons"
version = "0.20.11"
authors = ["Victor Berger <victor.berger@m4x.org>"]
repository = "https://github.com/smithay/wayland-rs"
documentation = "https://smithay.github.io/wayland-rs/wayland_commons/"
description = "Common types and structures used by wayland-client and wayland-server."
license = "MIT"
categories = ["gui", "api-bindings"]
keywords = ["wayland"]

[badges]
travis-ci = { repository = "smithay/wayland-rs" }

[dependencies]
wayland-sys = { version = "0.20.11", path = "../wayland-sys", optional = true }
downcast-rs = "1.0"
nix = "0.10"

[features]
default = ["native_lib"]
native_lib = [ "wayland-sys" ]
